targets:

  dev:

    default: true

    workspace:
      host: https://adb-4206962778623078.18.azuredatabricks.net/

    permissions:
      - group_name: Data Engineers
        level: CAN_MANAGE

    variables:
      catalog_name: "sandbox"
      cluster_id: "0729-074924-hc5rel6a"